---
- hosts: all
  become: yes
  tasks:
  - name: i want to insatall apache2 on ubuntu server
    apt:
     name: apache2
     state: present

  - name: i want to start webserver
    service:
     name: apache2